<%@ Page Title="HighLoad" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="Default.aspx.cs" Inherits="Default" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <table>
        <tr>
            <td valign="top" style="border:solid 1px black;">
                <asp:GridView ID="GridViewData" runat="server" PageSize="10" 
                    DataKeyNames="Id"
                    AllowPaging="true" 
                    AutoGenerateSelectButton="true" 
                    OnPageIndexChanging="HighLoadGridView_PageIndexChanging" 
                    OnSelectedIndexChanged="HighLoadGridView_SelectedIndexChanged" 
                    AutoGenerateColumns="false"  CellPadding="4" ForeColor="#333333" GridLines="None">
                    <EmptyDataTemplate>
                        <asp:Label runat="server">
                            There's no data to show in this view.
                        </asp:Label>
                    </EmptyDataTemplate>
                    <PagerSettings Mode="Numeric" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="ID" />
                        <asp:BoundField DataField="Number" HeaderText="Number" />
                        <asp:BoundField DataField="Name" HeaderText="Name" />
                        <asp:BoundField DataField="RevisionTime" HeaderText="Revision Time" />
                    </Columns>
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#2461BF" />  
                </asp:GridView> 
            </td>
            <td valign="top" style="border:solid 1px black;">
                <asp:DetailsView ID="DetailsViewData" runat="server"
                    DefaultMode="Insert"
                    AllowPaging="true" 
                    AutoGenerateRows="false"
                    HeaderText="Detailed Information" 
                    AutoGenerateEditButton="true" 
                    AutoGenerateDeleteButton="true"
                    OnItemCreated="DetailsViewData_ItemCreated" 
                    OnModeChanging="HighLoadDetailsView_ModeChanging" 
                    OnItemDeleting="HighLoadDetailsView_ItemDeleting" 
                    OnItemUpdating="HighLoadDetailsView_ItemUpdating" 
                    OnItemInserting="HighLoadDetailsView_ItemInserting" 
                    AutoGenerateInsertButton="true"  CellPadding="4" ForeColor="#333333" GridLines="None">
                    <PagerSettings Visible="false" />
                    <Fields>
                        <asp:BoundField DataField="Id" HeaderText="ID" InsertVisible="false" ReadOnly="true" />
                        <asp:BoundField DataField="Number" HeaderText="Number" />
                        <asp:BoundField DataField="Name" HeaderText="Name" />
                        <asp:BoundField DataField="RevisionTime" HeaderText="Revision Time" InsertVisible="false" ReadOnly="true" />
                    </Fields>
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
                    <RowStyle BackColor="White" />
                    <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="White" />
                </asp:DetailsView>
                <asp:CustomValidator runat="server" ID="InsertValidator" />  
            </td>
        </tr>
    </table>  
</asp:Content>
